# Generated by Django 3.0.5 on 2020-04-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=True, max_length=15, null=True, verbose_name='핸드폰'),
        ),
    ]
