# Generated by Django 2.2.11 on 2020-04-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('members', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.ManyToManyField(through='posts.PostLike', to='posts.PostRoom'),
        ),
        migrations.AddField(
            model_name='user',
            name='social',
            field=models.ManyToManyField(to='members.SocialLogin'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
