# Generated by Django 2.2.11 on 2020-03-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social',
            field=models.ManyToManyField(to='members.SocialLogin'),
        ),
    ]
