# Generated by Django 2.2.11 on 2020-03-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200330_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduce',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
