# Generated by Django 2.2.11 on 2020-03-30 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='포함 항목 물품')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalFee', models.IntegerField(verbose_name='관리비 합계')),
                ('controlPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.ControlPoint', verbose_name='포함 항목')),
            ],
        ),
        migrations.CreateModel(
            name='OptionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='옵션 항목 아이템')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='옵션 이미지')),
            ],
        ),
        migrations.CreateModel(
            name='PostAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadAddress', models.CharField(max_length=50)),
                ('detailAddress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SalesForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('deposit', models.IntegerField(null=True, verbose_name='보증금')),
                ('monthly', models.IntegerField(null=True, verbose_name='월세')),
                ('salePrice', models.IntegerField(null=True, verbose_name='매매 가격')),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySafetyFacilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='보안/안전 시설 아이템')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='시설 이미지')),
            ],
        ),
        migrations.CreateModel(
            name='PostRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('description', models.TextField(max_length=1000, verbose_name='설명')),
                ('floor', models.IntegerField(null=True, verbose_name='층 수')),
                ('totalFloor', models.IntegerField(null=True, verbose_name='건물 층 수')),
                ('area', models.IntegerField(verbose_name='전용 면적')),
                ('supplyArea', models.IntegerField(verbose_name='공급 면적')),
                ('shortRent', models.BooleanField()),
                ('parking', models.BooleanField(verbose_name='주차 유무')),
                ('parkingFee', models.IntegerField(verbose_name='주차 비용')),
                ('moveIn', models.DateTimeField(verbose_name='입주 가능 날짜')),
                ('heatingType', models.CharField(choices=[('Center', '중앙'), ('Division', '개별'), ('Area', '지역')], max_length=10, verbose_name='난방 종류')),
                ('pet', models.BooleanField(verbose_name='반려 동물')),
                ('elevator', models.BooleanField(verbose_name='엘레베이터')),
                ('multiFloor', models.BooleanField(verbose_name='복층')),
                ('pointRoom', models.BooleanField(verbose_name='1.5 룸, 주방 분리형')),
                ('builtIn', models.BooleanField(verbose_name='빌트 인')),
                ('veranda', models.BooleanField(verbose_name='베란다/발코니')),
                ('depositLoan', models.BooleanField(verbose_name='전세 자금 대출')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.PostAddress')),
                ('management', models.ManyToManyField(through='posts.MaintenanceFee', to='posts.ControlPoint')),
                ('option', models.ManyToManyField(to='posts.OptionItem', verbose_name='옵션 항')),
                ('salesForm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.SalesForm')),
                ('securitySafety', models.ManyToManyField(to='posts.SecuritySafetyFacilities')),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.PostRoom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='maintenancefee',
            name='postRoom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.PostRoom', verbose_name='해당 매물'),
        ),
    ]
