# Generated by Django 2.2.11 on 2020-03-25 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='포함 항목 물품')),
            ],
        ),
        migrations.CreateModel(
            name='OptionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='옵션 항목 아이템')),
            ],
        ),
        migrations.CreateModel(
            name='SalesForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('deposit', models.IntegerField(null=True, verbose_name='보증금')),
                ('monthly', models.IntegerField(null=True, verbose_name='월세')),
                ('salePrice', models.IntegerField(null=True, verbose_name='매매 가격')),
            ],
        ),
        migrations.CreateModel(
            name='PostRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('description', models.TextField(max_length=1000, verbose_name='설명')),
                ('floor', models.IntegerField(null=True, verbose_name='층 수')),
                ('totalFloor', models.IntegerField(null=True, verbose_name='건물 층 수')),
                ('area', models.IntegerField(verbose_name='전용 면적')),
                ('supplyArea', models.IntegerField(verbose_name='공급 면적')),
                ('shortRent', models.BooleanField()),
                ('parking', models.BooleanField(verbose_name='주차 유무')),
                ('parkingFee', models.IntegerField(verbose_name='주차 비용')),
                ('moveIn', models.DateTimeField(verbose_name='입주 가능 날짜')),
                ('option', models.ManyToManyField(to='posts.OptionItem', verbose_name='옵션 항')),
                ('salesForm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.SalesForm')),
            ],
        ),
    ]
