# Generated by Django 2.2.11 on 2020-04-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postroom',
            name='management',
            field=models.ManyToManyField(null=True, through='posts.MaintenanceFee', to='posts.AdministrativeDetail'),
        ),
        migrations.AlterField(
            model_name='postroom',
            name='securitySafety',
            field=models.ManyToManyField(null=True, through='posts.RoomSecurity', to='posts.SecuritySafetyFacilities'),
        ),
    ]
