# Generated by Django 3.0.5 on 2020-04-23 20:24

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broker',
            old_name='name',
            new_name='companyName',
        ),
        migrations.RenameField(
            model_name='broker',
            old_name='manager',
            new_name='managerName',
        ),
        migrations.AddField(
            model_name='broker',
            name='brokerage',
            field=models.CharField(max_length=30, null=True, verbose_name='중개등록번호'),
        ),
        migrations.AddField(
            model_name='broker',
            name='companyNumber',
            field=models.CharField(max_length=20, null=True, verbose_name='사업자 번호'),
        ),
        migrations.AddField(
            model_name='broker',
            name='dabangCreated_at',
            field=models.CharField(max_length=20, null=True, verbose_name='다방 가입일'),
        ),
        migrations.AddField(
            model_name='broker',
            name='image',
            field=models.ImageField(null=True, upload_to=posts.models.broker_image_path, verbose_name='이미지'),
        ),
        migrations.AddField(
            model_name='broker',
            name='successCount',
            field=models.CharField(max_length=10, null=True, verbose_name='거래 성공 횟수'),
        ),
    ]
