# Generated by Django 2.2.11 on 2020-03-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancefee',
            name='totalFee',
            field=models.IntegerField(verbose_name='관리비 합계'),
        ),
    ]
