# Generated by Django 2.2.11 on 2020-04-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postroom',
            name='type',
            field=models.CharField(max_length=10, null=True, verbose_name='매물 종류'),
        ),
    ]
