# Generated by Django 2.2.11 on 2020-03-25 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalFee', models.IntegerField(max_length=1024, verbose_name='관리비 합계')),
                ('controlPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.ControlPoint', verbose_name='포함 항목')),
                ('postRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.PostRoom', verbose_name='해당 매물')),
            ],
        ),
        migrations.AddField(
            model_name='postroom',
            name='management',
            field=models.ManyToManyField(through='posts.MaintenanceFee', to='posts.ControlPoint'),
        ),
    ]
