# Generated by Django 3.0.5 on 2020-04-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postroom',
            name='lat',
            field=models.FloatField(null=True, verbose_name='x축'),
        ),
        migrations.AddField(
            model_name='postroom',
            name='lng',
            field=models.FloatField(null=True, verbose_name='y축'),
        ),
    ]
