# Generated by Django 2.2.11 on 2020-04-13 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postroom',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.PostAddress'),
        ),
    ]
