# Generated by Django 2.2.11 on 2020-04-06 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testtitle', models.CharField(max_length=20, null=True, verbose_name='제목')),
            ],
        ),
        migrations.AddField(
            model_name='optionitem',
            name='postRoom',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='posts.PostRoom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securitysafetyfacilities',
            name='postRoom',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='posts.PostRoom'),
            preserve_default=False,
        ),
    ]
