# Generated by Django 3.0.5 on 2020-04-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200424_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='successCount',
            field=models.CharField(max_length=20, null=True, verbose_name='거래 성공 횟수'),
        ),
    ]
