# Generated by Django 2.2.11 on 2020-04-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200406_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionitem',
            name='postRoom',
        ),
        migrations.RemoveField(
            model_name='securitysafetyfacilities',
            name='postRoom',
        ),
        migrations.AddField(
            model_name='posttest',
            name='testdesc',
            field=models.TextField(null=True),
        ),
    ]
