# Generated by Django 2.2.11 on 2020-04-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postroom_parkingtf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postroom',
            old_name='textMoveIn',
            new_name='MoveInChar',
        ),
        migrations.RenameField(
            model_name='postroom',
            old_name='moveIn',
            new_name='moveInDate',
        ),
    ]
