# Generated by Django 2.2.11 on 2020-04-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200406_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postroom',
            name='heatingType',
            field=models.CharField(max_length=10, verbose_name='난방 종류'),
        ),
    ]
