# Generated by Django 2.2.11 on 2020-04-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200409_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postroom',
            name='areaInt',
        ),
        migrations.AlterField(
            model_name='postroom',
            name='builtIn',
            field=models.NullBooleanField(default=None, verbose_name='빌트인'),
        ),
        migrations.AlterField(
            model_name='postroom',
            name='depositLoan',
            field=models.NullBooleanField(default=None, verbose_name='전세 자금 대출'),
        ),
        migrations.AlterField(
            model_name='postroom',
            name='elevator',
            field=models.NullBooleanField(default=None, verbose_name='엘레베이터'),
        ),
        migrations.AlterField(
            model_name='postroom',
            name='multiFloor',
            field=models.NullBooleanField(default=None, verbose_name='복층 분리'),
        ),
        migrations.AlterField(
            model_name='postroom',
            name='parkingTF',
            field=models.NullBooleanField(default=None, verbose_name='주차 가능 유무'),
        ),
        migrations.AlterField(
            model_name='postroom',
            name='pet',
            field=models.NullBooleanField(default=None, verbose_name='반려동물'),
        ),
        migrations.AlterField(
            model_name='postroom',
            name='pointRoom',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='postroom',
            name='shortRent',
            field=models.NullBooleanField(default=None, verbose_name='단기임대'),
        ),
        migrations.AlterField(
            model_name='postroom',
            name='veranda',
            field=models.NullBooleanField(default=None, verbose_name='베란다/ 발코니'),
        ),
    ]
