# Generated by Django 2.2.11 on 2020-04-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200409_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postroom',
            name='multiFloor',
        ),
        migrations.RemoveField(
            model_name='postroom',
            name='pointRoom',
        ),
    ]
