# Generated by Django 2.2.11 on 2020-04-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200409_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postroom',
            old_name='parkingAccumulation',
            new_name='totalPark',
        ),
    ]
