# Generated by Django 2.2.11 on 2020-04-10 20:54

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200409_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=posts.models.post_image_path, verbose_name='방 이미지')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.PostRoom', verbose_name='해당 게시글')),
            ],
        ),
    ]
